### ISSUE TITLE
Crashes after loaded

### ISSUE THREAD

**Issue by uaevuon** [Sun-Research-University/sys-clk-Overlay#2] opened 2020-02-10 17:31 UTC
[01581355601_010000000007e51a.log](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4182196/01581355601_010000000007e51a.log)
[01581355415_010000000007e51a.log](https://github.com/Sun-Research-University/sys-clk-Overlay/files/4182197/01581355415_010000000007e51a.log)

Crashes right after sysclk overlay menu loaded on SMM2

**Comment by gabehxd** [comment] 2020-02-11 17:51
duplicate of #1

**Closed as completed by gabehxd** 2020-02-11 17:51 UTC
